name: flutter_riverpod_todo_app_my
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:

  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flex_color_scheme: ^7.2.0
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.5.0
  gap: ^3.0.1
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  intl: ^0.18.1
  path: ^1.8.3
  sqflite: ^2.3.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

